#!/bin/bash

args=()

for i; do
	case "$i" in
		-Wmissing-prototypes|-Wmissing-declarations|-Wstrict-prototypes|-Werror*)
			;;
		-fno-strict-aliasing)
			args+=("$i");;
		-f*|-m*)
			;;
		*)
			args+=("$i");;
	esac
done

exec gcc "${args[@]}"
